const ActionTypes = {
  ADD_USER: 'ADD_USER',
  ADD_EXERCISE_TEMPLATE: 'ADD_EXERCISE_TEMPLATE',
  ADD_EXERCISE: 'ADD_EXERCISE',
  ADD_PATIENT_EXERCISE: 'ADD_PATIENT_EXERCISE',

  UPDATE_EXERCISE_PROGRESS: 'UPDATE_EXERCISE_PROGRESS',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',

  SET_USER_ID: 'SET_USER_ID',
  SET_EXERCISE_ID: 'SET_EXERCISE_ID',
  SET_PATIENT_ID: 'SET_PATIENT_ID',

};

export default ActionTypes;
